<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<div class="alert fade in">
  <a class="close" data-dismiss="alert">×</a>
  <?php echo $this->__('There are no products matching the selection.') ?>
</div>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <div class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <div class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>  row-fluid">
        <div class="span12">
	    <div class="row-fluid">
	      <div class="span3">
	      <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a></div>
	      <div class="span9">
          <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>

                        <div class="row-fluid">
						    <div class="span12">
							    <div class="row-fluid">
							    <?php if($_product->getRatingSummary()): ?>
			                    <div class="span12"><?php echo $this->getReviewsSummaryHtml($_product) ?></div>
			                    <?php endif; ?>
							    <div class="row-fluid">
							    <div class="span5">
    							<div class="pull-right">
							    <?php if($_product->isSaleable()): ?>
		                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-mini btn-danger" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
			                    <?php else: ?>
			                        <p class="label label-importatnt"><span><?php echo $this->__('Out of stock') ?></span></p>
			                    <?php endif; ?>
                    			</div>
							    <strong><?php echo $this->getPriceHtml($_product, true) ?></strong>
							    </div>
								</div>
							    </div>
						    </div>
					    </div>

                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class=""><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <div class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="label label-info"><?php echo $this->__('Add to Wishlist') ?></a>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="label label-info"><?php echo $this->__('Add to Compare') ?></a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
	      </div>
	    </div><hr>
	    </div>
        </div>
    <?php endforeach; ?>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    </div>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <div class="products-grid row-fluid">
        <div class="span12">
	    <div class="row-fluid">
        <?php endif ?>
            <div class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> span4">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h6 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h6>
				<div class="">
	                <?php if($_product->getRatingSummary()): ?>
	                <div class="row-fluid"><div class="span12"><?php echo $this->getReviewsSummaryHtml($_product, 'short') ?></div></div>
	                <?php endif; ?>
	                	
	                	<div class="row-fluid"><div class="span12"><strong><?php echo $this->getPriceHtml($_product, true) ?></strong></div></div>
	                	
	                	<div class="row-fluid"><div class="span12">
	                	
	                    	                    
	                    <?php if($_product->isSaleable()): ?>
	                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-mini btn-danger" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
	                    <?php else: ?>
	                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
	                    <?php endif; ?>
	                    
	                    
	                    </div>
	                    </div>
	                    
	                    
	                    
	                    <div class="add-to-links">
	                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
	                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="label label-info"><?php echo $this->__('Add to Wishlist') ?></a>
	                        <?php endif; ?>
	                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
	                            <span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="label label-info"><?php echo $this->__('Add to Compare') ?></a>
	                        <?php endif; ?>
	                    </div>
                </div>
                
            </div>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </div>
        </div>
        </div><hr>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('div.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
