<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
/* @var $this Mage_Catalog_Block_Product_List_Toolbar */
?>

<?php if($this->getCollection()->getSize()): ?>

<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid toolbar">
            <div class="span3">

                <div class="input-prepend">
                        <span class="add-on">
                            <small>
                                <?php if($this->getLastPageNum()>1): ?>
                                <?php echo $this->__('%s-%s (%s)', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                                <?php else: ?>
                                <strong><?php echo $this->__('%s', $this->getTotalNum()) ?></strong>
                                <?php endif; ?>
                            </small>
                        </span>
                    <select class="span1" onchange="setLocation(this.value)">
                        <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                        <option value="<?php echo $this->getLimitUrl($_key) ?>"
                            <?php if($this->isLimitCurrent($_key)): ?> selected="selected"
                            <?php endif ?>>
                            <?php echo $_limit ?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                </div>

            </div>
            <div class="span6">
                <?php echo $this->getPagerHtml() ?>&nbsp;
            </div>
            <div class="span2">
                <div class="input-prepend">
                                        <span class="add-on">

                                            <?php if($this->getCurrentDirection() == 'desc'): ?>
                                            <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>">
                                                <span class="icon-arrow-down"></span>
                                            </a>
                                            <?php else: ?>
                                            <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>">
                                                <span class="icon-arrow-up"></span>
                                            </a>
                                            <?php endif; ?>
                                        </span>
                    <select class="span1" onchange="setLocation(this.value)">
                        <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                        <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>" <?php if($this->isOrderCurrent($_key)): ?> selected="selected" <?php endif; ?>>
                            <?php echo $this->__($_order) ?>
                        </option>
                        <?php endforeach; ?>
                    </select>

                </div>


            </div>
            <div class="span1">
                <?php if( $this->isEnabledViewSwitcher() ): ?>
                <span class="the-icons">
                    <?php $_modes = $this->getModes(); ?>
                    <?php if($_modes && count($_modes)>1): ?>
                    <?php foreach ($this->getModes() as $_code=>$_label): ?>

                        <?php if($_code == (string)'grid'):?>
                            <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><i class="icon-th-large"></i></a>&nbsp;
                            <?php else: ?>
                            <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><i class="icon-align-justify"></i></a>&nbsp;
                            <?php endif; ?>

                        <?php endforeach; ?>
                    <?php endif; ?>
                </span>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<?php endif ?>